name: pysam-install-via-bioconda

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 5
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10"]
    name: Python ${{ matrix.python-version }} ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - uses: conda-incubator/setup-miniconda@v2
        with:
          channels: conda-forge,bioconda,defaults
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          conda install -y -n base conda-libmamba-solver
          conda config --set solver libmamba
          conda create -y -n testenv python=${{ matrix.python-version }}
          conda install -y -n testenv -c bioconda pysam

      - name: Run test
        run: |
          conda activate testenv
          python -c "import pysam; print(pysam.__version__)"
