name: Install Bioconda Package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.8
          activate-environment: myenv
          environment-file: environment.yml
          channels: bioconda, conda-forge, defaults

      - name: Install Bioconda Package
        run: |
          conda install -c bioconda bowtie -y
          bowtie --version || exit 1
