name: pysam-install-via-bioconda

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    name: Python ${{ matrix.python-version }} ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: mamba-org/setup-micromamba@v1.1.0
        with:
          environment-name: ${{ matrix.python-version }}
          create-args: python=${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          micromamba install -y -c bioconda pysam

      - name: Run pytest
        run: |
          python -c "import pysam; print(pysam.__version__)"
