name: Run example by current DAJIN2 package

on:
    push:

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            max-parallel: 2
            matrix:
                os: [ubuntu-latest, macos-latest]
                python-version: ["3.x"]
        name: Python ${{ matrix.python-version }} on ${{ matrix.os }}

        defaults:
            run:
                shell: bash -l {0}

        steps:
            - uses: actions/checkout@v4

            # Set up Python environment using actions/setup-python
            - uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}

            # Install dependencies
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install DAJIN2==0.5.5

            - name: Download example dataset
              run: |
                  if ! [ -d example_single ]; then
                      curl -LJO https://github.com/akikuno/DAJIN2/raw/main/examples/example_single.tar.gz
                      tar -xf example_single.tar.gz
                  fi

            - name: Execute tests
              env:
                  PYTHONPATH: src
              run: |
                  # Run DAJIN2 with specified parameters
                  time DAJIN2 \
                      --control example_single/control \
                      --sample example_single/sample \
                      --allele example_single/stx2_deletion.fa \
                      --name stx2_deletion \
                      --genome mm39 \
                      --threads 4 \
                      --debug || exit 1
