name: Run example by current DAJIN2 package

on:
    push:
    schedule:
        - cron: "0 2 * * 1" # The task runs at 2 a.m. every Monday.

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            max-parallel: 10
            matrix:
                os: [ubuntu-latest, macos-latest]
                python-version: ["3.12"]
        name: Python ${{ matrix.python-version }} on ${{ matrix.os }}

        defaults:
            run:
                shell: bash -l {0}

        steps:
            - uses: actions/checkout@v4
            - uses: conda-incubator/setup-miniconda@v3
              with:
                  python-version: ${{ matrix.python-version }}
                  miniconda-version: "latest"
                  activate-environment: test-env
                  channels: bioconda, conda-forge, defaults

            - name: Setup conda environment
              run: |
                  conda create -y -n env-dajin2 python=${{ matrix.python-version }} pip pytest

            - name: Install weasyprint on macos-latest🍎
              if: runner.os == 'macOS'
              run: |
                  conda install -n env-dajin2 weasyprint

            - name: Execute tests
              env:
                  PYTHONPATH: src
              run: |
                  conda activate env-dajin2

                  # Use pip because conda does not support pyproject.toml.
                  pip install DAJIN2==0.5.4

                  # Donwload the example dataset

                  if ! [ -d example_single ]; then
                      curl -LJO https://github.com/akikuno/DAJIN2/raw/main/examples/example_single.tar.gz
                      tar -xf example_single.tar.gz
                  fi

                  # Run DAJIN2
                  time DAJIN2 \
                      --control example_single/control \
                      --sample example_single/sample \
                      --allele example_single/stx2_deletion.fa \
                      --name stx2_deletion \
                      --genome mm39 \
                      --threads 4 \
                      --debug || exit 1
