name: E2E test for Stx2 deletion

on:
    push:

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            max-parallel: 2
            matrix:
                os: [ubuntu-latest, macos-latest]
                python-version: ["3.13"]
        name: Python ${{ matrix.python-version }} on ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Create and activate virtual environment
              run: |
                  python -m venv env
                  source env/bin/activate
                  pip install --upgrade pip
                  pip install pytest

            - name: Install DAJIN2 and dependencies
              run: |
                  source env/bin/activate
                  pip install -e .  # Install DAJIN2 in editable mode

            - name: Download example dataset
              run: |
                  if [ ! -d example_single ]; then
                    curl -LJO https://github.com/akikuno/DAJIN2/raw/main/examples/example_single.tar.gz
                    tar -xf example_single.tar.gz
                  fi

            - name: Run DAJIN2 with parameters
              env:
                  PYTHONPATH: src
              run: |
                  source env/bin/activate
                  time DAJIN2 \
                      --control example_single/control \
                      --sample example_single/sample \
                      --allele example_single/stx2_deletion.fa \
                      --name stx2_deletion \
                      --genome mm39 \
                      --threads 4 \
                      --debug || exit 1
